90

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,58 +1,11 @@
 name: Build and Package
 
-on: [push]
+on:
+  push:
+    branches:
+      - main
 
 jobs:
-  build_macos:
-    runs-on: macos-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Setup environment
-        run: |
-          brew install cmake
-
-      - name: Configure project with CMake
-        run: |
-          mkdir build
-          cd build
-          cmake .. || { echo "CMake configuration failed"; exit 1; }
-
-      - name: Build and create package
-        run: |
-          cd build
-          cmake --build . || { echo "Build failed"; exit 1; }
-          cpack -G PKG || { echo "Package creation failed"; exit 1; }
-
-      - name: List files after build
-        run: |
-          cd build
-          echo "Current directory:"
-          pwd
-          echo "Contents of the build directory:"
-          ls -alh
-
-      - name: Set .pkg file path
-        id: set_pkg_path
-        run: |
-          cd build
-          PKG_FILE=$(find . -name "*.pkg" | head -n 1)
-          if [[ -z "$PKG_FILE" ]]; then
-            echo "No .pkg file found."
-            exit 1
-          else
-            echo "pkg_path=$(realpath "$PKG_FILE")" >> $GITHUB_ENV
-            echo "pkg_path=$(realpath "$PKG_FILE")" >> $GITHUB_OUTPUT
-            echo "Found package: $PKG_FILE"
-          fi
-
-      - name: Upload .pkg artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: my-macos-package
-          path: ${{ steps.set_pkg_path.outputs.pkg_path }}
-
   build_ubuntu:
     runs-on: ubuntu-latest
     steps:
@@ -63,6 +16,7 @@ jobs:
         run: |
           sudo apt-get update
           sudo apt-get install -y cmake
+          sudo apt-get install -y libboost-all-dev # Установка Boost
 
       - name: Configure project with CMake
         run: |
@@ -70,36 +24,39 @@ jobs:
           cd build
           cmake .. || { echo "CMake configuration failed"; exit 1; }
 
-      - name: Build and create package
+      - name: Build the project
         run: |
           cd build
           cmake --build . || { echo "Build failed"; exit 1; }
+
+      - name: Package the project
+        run: |
+          cd build
           cpack -G DEB || { echo "Package creation failed"; exit 1; }
 
-      - name: List files after build
+  build_macos:
+    runs-on: macos-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Setup environment
+        run: |
+          brew install cmake
+          brew install boost # Установка Boost
+
+      - name: Configure project with CMake
+        run: |
+          mkdir build
+          cd build
+          cmake .. || { echo "CMake configuration failed"; exit 1; }
+
+      - name: Build the project
         run: |
           cd build
-          echo "Current directory:"
-          pwd
-          echo "Contents of the build directory:"
-          ls -alh
+          cmake --build . || { echo "Build failed"; exit 1; }
 
-      - name: Set .deb file path
-        id: set_deb_path
+      - name: Package the project
         run: |
           cd build
-          DEB_FILE=$(find . -name "*.deb" | head -n 1)
-          if [[ -z "$DEB_FILE" ]]; then
-            echo "No .deb file found."
-            exit 1
-          else
-            echo "deb_path=$(realpath "$DEB_FILE")" >> $GITHUB_ENV
-            echo "deb_path=$(realpath "$DEB_FILE")" >> $GITHUB_OUTPUT
-            echo "Found package: $DEB_FILE"
-          fi
-
-      - name: Upload .deb artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: my-ubuntu-package
-          path: ${{ steps.set_deb_path.outputs.deb_path }}
+          cpack -G PKG || { echo "Package creation failed"; exit 1; }
