88

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,26 +1,29 @@
-name: 'C++ CI'
+name: Build and Package
 
-on:
-  push:
-    branches:
-      - main
-      - feature/github_actions
+on: [push]
 
 jobs:
   build_macos:
     runs-on: macos-latest
-    outputs:
-      pkg_path: ${{ steps.set_pkg_path.outputs.pkg_path }}
     steps:
-      - uses: actions/checkout@v3
-        with:
-          submodules: true
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-      - run: brew update && brew install boost
+      - name: Setup environment
+        run: |
+          brew install cmake
 
-      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
-      - run: cmake --build .
-      - run: cmake --build . --target package
+      - name: Build and create package
+        run: |
+          cmake --build . || { echo "Build failed"; exit 1; }
+          cpack -G PKG || { echo "Package creation failed"; exit 1; }
+
+      - name: List files after build
+        run: |
+          echo "Current directory:"
+          pwd
+          echo "Contents of the build directory:"
+          ls -alh
 
       - name: Set .pkg file path
         id: set_pkg_path
@@ -32,28 +35,37 @@ jobs:
           else
             echo "pkg_path=$(realpath "$PKG_FILE")" >> $GITHUB_ENV
             echo "pkg_path=$(realpath "$PKG_FILE")" >> $GITHUB_OUTPUT
+            echo "Found package: $PKG_FILE"
           fi
 
       - name: Upload .pkg artifact
         uses: actions/upload-artifact@v3
         with:
           name: my-macos-package
-          path: ${{ steps.set_pkg_path.outputs.pkg_path }} # Используйте правильный доступ к выходному значению
+          path: ${{ steps.set_pkg_path.outputs.pkg_path }}
 
   build_ubuntu:
     runs-on: ubuntu-latest
-    outputs:
-      deb_path: ${{ steps.set_deb_path.outputs.deb_path }}
     steps:
-      - uses: actions/checkout@v3
-        with:
-          submodules: true
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-      - run: sudo apt-get update && sudo apt-get install libboost-test-dev -y
-      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
-      - run: cmake --build .
-      - name: Create Debian Package
-        run: cpack -G DEB
+      - name: Setup environment
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y cmake
+
+      - name: Build and create package
+        run: |
+          cmake --build . || { echo "Build failed"; exit 1; }
+          cpack -G DEB || { echo "Package creation failed"; exit 1; }
+
+      - name: List files after build
+        run: |
+          echo "Current directory:"
+          pwd
+          echo "Contents of the build directory:"
+          ls -alh
 
       - name: Set .deb file path
         id: set_deb_path
@@ -65,26 +77,11 @@ jobs:
           else
             echo "deb_path=$(realpath "$DEB_FILE")" >> $GITHUB_ENV
             echo "deb_path=$(realpath "$DEB_FILE")" >> $GITHUB_OUTPUT
+            echo "Found package: $DEB_FILE"
           fi
 
       - name: Upload .deb artifact
         uses: actions/upload-artifact@v3
         with:
           name: my-ubuntu-package
-          path: ${{ steps.set_deb_path.outputs.deb_path }} # Используйте правильный доступ к выходному значению
-  
-  upload_artifacts:
-    needs: [build_macos, build_ubuntu]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Download artifacts from macOS and Ubuntu builds
-        uses: actions/download-artifact@v3
-        with:
-          name: my-macos-package
-          path: ./macos-artifacts
-      
-      - name: Download artifacts from Ubuntu build
-        uses: actions/download-artifact@v3
-        with:
-          name: my-ubuntu-package
-          path: ./ubuntu-artifacts
+          path: ${{ steps.set_deb_path.outputs.deb_path }}
