89

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -13,13 +13,21 @@ jobs:
         run: |
           brew install cmake
 
+      - name: Configure project with CMake
+        run: |
+          mkdir build
+          cd build
+          cmake .. || { echo "CMake configuration failed"; exit 1; }
+
       - name: Build and create package
         run: |
+          cd build
           cmake --build . || { echo "Build failed"; exit 1; }
           cpack -G PKG || { echo "Package creation failed"; exit 1; }
 
       - name: List files after build
         run: |
+          cd build
           echo "Current directory:"
           pwd
           echo "Contents of the build directory:"
@@ -28,6 +36,7 @@ jobs:
       - name: Set .pkg file path
         id: set_pkg_path
         run: |
+          cd build
           PKG_FILE=$(find . -name "*.pkg" | head -n 1)
           if [[ -z "$PKG_FILE" ]]; then
             echo "No .pkg file found."
@@ -55,13 +64,21 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y cmake
 
+      - name: Configure project with CMake
+        run: |
+          mkdir build
+          cd build
+          cmake .. || { echo "CMake configuration failed"; exit 1; }
+
       - name: Build and create package
         run: |
+          cd build
           cmake --build . || { echo "Build failed"; exit 1; }
           cpack -G DEB || { echo "Package creation failed"; exit 1; }
 
       - name: List files after build
         run: |
+          cd build
           echo "Current directory:"
           pwd
           echo "Contents of the build directory:"
@@ -70,6 +87,7 @@ jobs:
       - name: Set .deb file path
         id: set_deb_path
         run: |
+          cd build
           DEB_FILE=$(find . -name "*.deb" | head -n 1)
           if [[ -z "$DEB_FILE" ]]; then
             echo "No .deb file found."
